CREATE TABLE IF NOT EXISTS client (
   id INTEGER PRIMARY KEY,
   ip TEXT NOT NULL,
   port INTEGER NOT NULL,
   last_seen DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS history (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   client_id INTEGER NOT NULL,
   question TEXT,
   answer TEXT,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE CASCADE
);